# Write your MySQL query statement below
SELECT ID,
MAX(IF(month="JAN",REVENUE,NULL)) AS JAN_REVENUE,
MAX(IF(month="FEB",REVENUE,NULL)) AS FEB_REVENUE,
MAX(IF(month="MAR",REVENUE,NULL)) AS MAR_REVENUE,
MAX(IF(month="APR",REVENUE,NULL)) AS APR_REVENUE,
MAX(IF(month="MAY",REVENUE,NULL)) AS MAY_REVENUE,
MAX(IF(month="JUN",REVENUE,NULL)) AS JUN_REVENUE,
MAX(IF(month="JUL",REVENUE,NULL)) AS JUL_REVENUE,
MAX(IF(month="AUG",REVENUE,NULL)) AS AUG_REVENUE,
MAX(IF(month="SEP",REVENUE,NULL)) AS SEP_REVENUE,
MAX(IF(month="OCT",REVENUE,NULL)) AS OCT_REVENUE,
MAX(IF(month="NOV",REVENUE,NULL)) AS NOV_REVENUE,
MAX(IF(month="DEC",REVENUE,NULL)) AS DEC_REVENUE
FROM DEPARTMENT
GROUP BY ID
ORDER BY ID